server.port=8181
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.datasource.url=jdbc:postgresql://localhost:5432/project_db
spring.datasource.username=postgres
spring.datasource.password=admin
# ???????????? JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# ??????? ???? ??? Spring Data REST
spring.data.rest.base-path=/api
# ????????? ???? ??? JWT (??????? ??? ?????? ?3)
jwt.secret=my_very_secure_secret_key_1234567890_fashion_lab_project